### ISSUE TITLE
Configurable Problem Info Blocks

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#1]
Add a Contest configuration option: "Show Problem Info Blocks" with two values: On and Off. When On, problem information blocks "Problem Statement," "Input Format," "Output Format," and "Constraints" appear. When Off, problem information blocks do not appear.

**Comment by mjoha563** [comment]
What pages does this effect? Does this effect what an Admin user would see when creating/editing a problem? Or would this only effect what a contestant would see when participating in a contest?

**Comment by sschaub** [comment]
> What pages does this effect?

This would affect both the contestant and admin problem pages.
