### ISSUE TITLE
Contestant submission history table

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#13]
In the contestant /submissions view, replace the current display with a table that contains the following columns:
* Problem Title
* Submission date/time
* Language
* Result

Sort the table by problem, then submission date/time (most recent on top).

Result should be the judging result, unless the submission status is "review," in which case it should be "Pending review".

When the user clicks on an entry in the table, display a popup that shows the source code. For inspiration on how to do this part, review the /judge view, which does something similar.

**Comment by zrev2220** [comment]
Should the popup window also display the results of each test case (without the test data of course) as is displayed when you submit a problem?

**Comment by sschaub** [comment]
> Should the popup window also display the results of each test case

No.
