### ISSUE TITLE
Detailed Contest Report

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#14]
Add a button to the leaderboard screen labeled "Detailed Report". When clicked, this should display a report like this:

* [Sample report](https://protect.bju.edu/wiki/download/attachments/1737261/MU2018Standings.pdf?version=1&modificationDate=1519675981000)

*Clarifications to original request:*

Note that an HTML report is preferable.

Replace "Team" and "Team ID" with "Contestant" and "Contestant ID". While the contest is running, "Contestant" should be hidden.

**Comment by levilohmeyer** [comment]
I can't find any Python modules that would generate a nice-looking PDF for the detailed report feature. Were those tables generated in Excel? Does the report have to be that fancy or can we generate ASCII tables and output them to a PDF?

**Comment by sschaub** [comment]
> Does the report have to be that fancy or can we generate ASCII tables and output them to a PDF?

A PDF report is not required. An HTML report with a table is fine (and actually preferable).

**Comment by andrew-avinante** [comment]
Do you want us to replace "Team" and "Team ID" with "User" and "User ID"?

**Comment by sschaub** [comment]
> Do you want us to replace "Team" and "Team ID" with "User" and "User ID"?

Good question. Let's replace with "Contestant" and "Contestant ID". I'll also add a note above that, while the contest is running, "Contestant" should be hidden.

**Comment by andrew-avinante** [comment]
Do you want it to be vanilla HTML without the css?

**Comment by sschaub** [comment]
> Do you want it to be vanilla HTML without the css?

My preference would be for it to have the standard header and footer of the open-contest system.
