### ISSUE TITLE
Contestant Submission Details Popup Does Not Appear

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#42]
1. Login as a contestant > My Submissions > Click on a submission

Expected: Popup that displays details about submission
Actual: Nothing happens (404 error in log)

**Comment by hnduke** [comment]
[Commit 0x94eecf0](https://github.com/bjucps/open-contest/commit/94eecf0eae96f2d2ae9cd420c8d78a4653106751) fixes this issue.

**Comment by sschaub** [comment]
Verified fix. Thank you!
