### ISSUE TITLE
Rejudge individual submission fails

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#43]
1. Login as admin > Judge 
2. Click on a submission to open the popup, then choose Rejudge.

Expected: System rejudges submission.
Actual: Error appears in log

**Comment by hnduke** [comment]
[Commit 0x82d939e](https://github.com/bjucps/open-contest/commit/82d939e73bb5a0e8b52dad8618b79252ed57c285) fixes this issue.

**Comment by hnduke** [comment]
I believe [commit 0x818f4d0](https://github.com/bjucps/open-contest/commit/818f4d031028b9987bb62c68be2d3ad8f8bcd0a1) fixes the issue for real this time. I know I got an alert with the new verdict.

**Comment by sschaub** [comment]
Looks good now!
